export const serviceConstant = {
    SERVICE_LIST_REQUEST: 'SERVICE_LIST_REQUEST',
    SERVICE_LIST_SUCCESS: 'SERVICE_LIST_SUCCESS',
    SERVICE_LIST_FAILURE: 'SERVICE_LIST_FAILURE',
    SERVICE_DETAILS_REQUEST: 'SERVICE_DETAILS_REQUEST',
    SERVICE_DETAILS_SUCCESS: 'SERVICE_DETAILS_SUCCESS',
    SERVICE_DETAILS_FAILURE: 'SERVICE_DETAILS_FAILURE'
}